name: todachic_clean
description: Todachic Clean - Gestión de inventario y ventas
publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.6.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts
  fl_chart: ^0.65.0
  
  # Utilities
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.2
  
  # Code generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true